insert into public.shop_products (
  title,
  slug,
  description,
  short_description,
  image_url,
  price_cents,
  currency,
  inventory_count,
  status,
  featured,
  sort_order
)
values
  (
    'Sage Stuk Verdriet tote bag',
    'sage-stuk-verdriet-tote-bag',
    'Een tweede tote in zachte sage kleurstelling, met het Stuk Verdriet logo in warm paper. Stevig genoeg voor dagelijks gebruik en rustig genoeg voor de collectie.',
    'Sage katoenen tas met warm paper logo en stevige canvas afwerking.',
    '/shop/sage-tote-bag.webp',
    2195,
    'eur',
    40,
    'published',
    false,
    7
  ),
  (
    'Crossbody bewaar pouch',
    'crossbody-bewaarpouch',
    'Een kleine katoenen crossbody pouch voor sleutels, telefoon, notitieboekje of iets dat je dichtbij wilt dragen. Naturel canvas met sage band en subtiel logo.',
    'Kleine crossbody pouch voor dagelijkse spullen of een klein aandenken.',
    '/shop/crossbody-bewaarpouch.webp',
    2495,
    'eur',
    35,
    'published',
    false,
    8
  ),
  (
    'Troostdeken',
    'troostdeken',
    'Een zachte katoenen deken in warme paper tinten met sage randstiksel en een klein geweven Stuk Verdriet label. Voor op de bank, naast bed of bij een rustig moment.',
    'Zachte katoenen deken met sage randstiksel en klein logo-label.',
    '/shop/troostdeken.webp',
    4995,
    'eur',
    16,
    'published',
    false,
    9
  ),
  (
    'Herinnerboekje',
    'herinnerboekje',
    'Een linnen notitieboekje voor herinneringen, zinnen, namen, rituelen en kleine momenten die je wilt bewaren. Met blanco pagina''s en een ingetogen debossed logo.',
    'Linnen boekje voor herinneringen, rituelen en woorden die mogen blijven.',
    '/shop/herinnerboekje.webp',
    2295,
    'eur',
    30,
    'published',
    false,
    10
  ),
  (
    'Stil moment mok',
    'stil-moment-mok',
    'Een matte keramieken mok met pine groene binnenkant en klein Stuk Verdriet logo. Voor koffie, thee of een pauze waarin niets hoeft.',
    'Matte keramieken mok voor koffie, thee en stille momenten.',
    '/shop/stil-moment-mok.webp',
    1795,
    'eur',
    48,
    'published',
    false,
    11
  ),
  (
    'Woorden kaartenset',
    'woorden-kaartenset',
    'Een set stevige kaarten en enveloppen in Stuk Verdriet tinten. Om iets kleins te sturen wanneer grote woorden niet passen.',
    'Kaarten en enveloppen voor steun, herinnering en nabijheid.',
    '/shop/woorden-kaartenset.webp',
    1495,
    'eur',
    60,
    'published',
    false,
    12
  ),
  (
    'Linnen bewaarzakje',
    'linnen-bewaarzakje',
    'Een klein linnen trekkoordzakje voor sieraden, kaartjes, steentjes of andere kleine herinneringen. Naturel met sage koord en subtiel logo.',
    'Klein linnen zakje voor tastbare herinneringen en kleine items.',
    '/shop/linnen-bewaarzakje.webp',
    1295,
    'eur',
    70,
    'published',
    false,
    13
  ),
  (
    'Ritueelset lucifers en snuffer',
    'ritueelset-lucifers-en-snuffer',
    'Een klein accessoiresetje voor kaarsrituelen: lucifers in pine groene sleeve, een messingkleurige snuffer en een rustige tray.',
    'Lucifers en snuffer als klein accessoiresetje voor kaarsrituelen.',
    '/shop/ritueel-lucifers-snuffer.webp',
    1995,
    'eur',
    28,
    'published',
    false,
    14
  ),
  (
    'Logo emaille pin steunproduct',
    'logo-emaille-pin-steunproduct',
    'Een kleine emaille pin van het Stuk Verdriet logo. Een laagdrempelig steunproduct dat je op een tas, jas of etui kunt dragen.',
    'Kleine emaille pin van het logo als laagdrempelig steunproduct.',
    '/shop/logo-emaille-pin.webp',
    795,
    'eur',
    90,
    'published',
    false,
    15
  ),
  (
    'Mini ritueelset',
    'mini-ritueelset',
    'Een kleine box met mini-kaars, blanco kaartje, linnen zakje en herinnersteen. Voor een rustig moment thuis of als ingetogen steun aan iemand anders.',
    'Kleine ritueelbox met mini-kaars, kaartje, zakje en herinnersteen.',
    '/shop/mini-ritueelset.webp',
    2795,
    'eur',
    22,
    'published',
    false,
    16
  )
on conflict (slug) do update
set title = excluded.title,
    description = excluded.description,
    short_description = excluded.short_description,
    image_url = excluded.image_url,
    price_cents = excluded.price_cents,
    currency = excluded.currency,
    inventory_count = excluded.inventory_count,
    status = excluded.status,
    featured = excluded.featured,
    sort_order = excluded.sort_order,
    updated_at = now();
